barrel/views.py
from flask import (
    Blueprint, render_template, request, flash, redirect,
    url_for, abort)

from barrel.forms import MonkeyForm, ConfirmForm, FilterForm
from barrel import database, helpers


crud = Blueprint('crud', __name__, template_folder='templates')


PAGE_SIZE = 5


@crud.route('/monkey/<int:mnk_id>/friendship/<int:friend_id>/best',
            methods=['GET', 'POST'])
def set_best_friend(mnk_id: int, friend_id: int):
    if mnk_id == friend_id or not database.has_friendship(mnk_id, friend_id):
        abort(404)

    mnk = helpers.get_monkey_or_404(mnk_id)
    fmnk = helpers.get_monkey_or_404(friend_id)
    form = ConfirmForm()
    if form.validate_on_submit():
        database.set_best_friend(mnk, fmnk)

        flash(f'Monkey "{mnk.name}" and "{fmnk.name}" are best friends now.',
              'success')
        return redirect(url_for('crud.view', pk=mnk.id))

    return render_template('crud/set_best_friend.html',
                           monkey=mnk,
                           friend=fmnk,
                           form=form)


@crud.route('/monkey/<int:mnk_id>/friendship/<int:friend_id>/undo',
            methods=['GET', 'POST'])
def undo_friendship(mnk_id: int, friend_id: int):
    if mnk_id == friend_id or not database.has_friendship(mnk_id, friend_id):
        abort(404)

    mnk = helpers.get_monkey_or_404(mnk_id)
    fmnk = helpers.get_monkey_or_404(friend_id)
    form = ConfirmForm()
    if form.validate_on_submit():
        database.destroy_friendship(mnk, fmnk)
        flash(f'Monkey "{mnk.name}" are not friends "{fmnk.name}" anymore.',
              'warning')
        return redirect(url_for('crud.view', pk=mnk.id))

    return render_template('crud/undo_friendship.html',
                           monkey=mnk,
                           friend=fmnk,
                           form=form)


@crud.route('/monkey/<int:mnk_id>/friendship/<int:friend_id>/make',
            methods=['GET', 'POST'])
def make_friendship(mnk_id: int, friend_id: int):
    if mnk_id == friend_id or database.has_friendship(mnk_id, friend_id):
        abort(404)

    mnk = helpers.get_monkey_or_404(mnk_id)
    fmnk = helpers.get_monkey_or_404(friend_id)
    form = ConfirmForm()
    if form.validate_on_submit():
        database.make_friendship(mnk, fmnk)
        flash(f'Monkey "{mnk.name}" are friends "{fmnk.name}" now.', 'success')
        return redirect(url_for('crud.view', pk=mnk.id))

    return render_template('crud/make_friendship.html',
                           monkey=mnk,
                           friend=fmnk,
                           form=form)


@crud.route('/monkeys/create', methods=['GET', 'POST'])
def create():
    form = MonkeyForm(request.form)
    if form.validate_on_submit():
        mnk = database.create_monkey(form.name.data,
                                     form.age.data,
                                     form.email.data)
        flash(f'Monkey "{mnk.name}" created.', 'success')
        return redirect(url_for('crud.dashboard'))
    return render_template('crud/create.html', form=form)


@crud.route('/')
def dashboard():
    filterform = FilterForm(request.args)

    if filterform.validate():
        offset = filterform.offset.data
        sort_by = filterform.sort_by.data
        sort = filterform.sort.data
    else:
        offset = 0
        sort_by = 'name'
        sort = 'asc'

    count = database.count_monkeys()
    pages = range(0, count, PAGE_SIZE)
    monkeys = database.get_monkeys_data(sort_by, sort, offset, PAGE_SIZE)

    return render_template('crud/dashboard.html',
                           filterform=filterform,
                           monkeys=monkeys,
                           offset=offset,
                           pages=pages)


@crud.route('/monkey/<int:pk>')
def view(pk: int):
    monkey = helpers.get_monkey_or_404(pk)
    network = database.get_monkey_network(pk)
    return render_template('crud/view.html', monkey=monkey, network=network)


@crud.route('/monkey/<int:pk>/edit', methods=['GET', 'POST'])
def edit(pk: int):
    mnk = helpers.get_monkey_or_404(pk)
    form = MonkeyForm(name=mnk.name, age=mnk.age, email=mnk.email)
    if form.validate_on_submit():
        database.update_monkey(mnk.id,
                               name=form.name.data,
                               age=form.age.data,
                               email=form.email.data)
        flash(f'Monkey "{mnk.name}" updated.', 'success')
        return redirect(url_for('crud.dashboard'))

    return render_template('crud/edit.html', monkey=mnk, form=form)


@crud.route('/monkey/<int:pk>/delete', methods=['GET', 'POST'])
def delete(pk: int):
    mnk = helpers.get_monkey_or_404(pk)
    form = ConfirmForm()
    if form.validate_on_submit():
        database.delete_monkey(mnk.id)
        flash(f'Monkey "{mnk.name}" deleted.', 'warning')
        return redirect(url_for('crud.dashboard'))

    return render_template('crud/delete.html', monkey=mnk, form=form)

barrel/templates/crud/includes/list.html
<div class="container">
    {% if monkeys %}
        <table class="table table-borderless">
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">
                    <a href="?offset={{ offset }}&sort=desc&sort_by=name" class="btn btn-sm btn-outline-info">
                        ▼
                    </a>
                    Name
                    <a href="?offset={{ offset }}&sort=asc&sort_by=name" class="btn btn-sm btn-outline-info">
                        ▲
                    </a>
                </th>
                <th scope="col">Age</th>
                <th scope="col">Email</th>
                <th scope="col">
                    <a href="?offset={{ offset }}&sort=desc&sort_by=best_friend_name" class="btn btn-sm btn-outline-info">
                        ▼
                    </a>
                    Best Friend
                    <a href="?offset={{ offset }}&sort=asc&sort_by=best_friend_name" class="btn btn-sm btn-outline-info">
                        ▲
                    </a>
                </th>
                <th scope="col">
                    <a href="?offset={{ offset }}&sort=desc&sort_by=friends_count" class="btn btn-sm btn-outline-info">
                        ▼
                    </a>
                    Friends Count
                    <a href="?offset={{ offset }}&sort=asc&sort_by=friends_count" class="btn btn-sm btn-outline-info">
                        ▲
                    </a>
                </th>
                </tr>
            </thead>
            <tbody>
                {% for mnkdata in monkeys %}
                    <tr>
                    <th scope="row">{{ mnkdata.monkey.id }}</th>
                    <td>
                        {{ mnkdata.monkey.name }}
                    </td>
                    <td>{{ mnkdata.monkey.age }}</td>
                    <td>{{ mnkdata.monkey.email }}</td>
                    <td>{{ mnkdata.best_friend_name }}</td>
                    <td>{{ mnkdata.friends_count }}</td>
                    <th>
                        <a href="{{ url_for('crud.edit', pk=mnkdata.monkey.id) }}" class="btn btn-sm btn-outline-primary">Edit</a>
                        <a href="{{ url_for('crud.view', pk=mnkdata.monkey.id) }}" class="btn btn-sm btn-outline-info">View</a>
                        <a href="{{ url_for('crud.delete', pk=mnkdata.monkey.id) }}" class="btn btn-sm btn-outline-danger">Remove</a>
                    </th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
    <p><em>There is no Monkey available</em> Click <a href="{{ url_for('crud.create') }}">here</a> to create one.</p>

    {% endif %}
</div>

barrel/templates/crud/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{{ url_for('crud.dashboard') }}">
        Monkeys Network
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% with url = url_for('crud.dashboard') %}
            <li class="nav-item {% if url == request.path %}active{% endif %}">
                <a class="nav-link" href="{{ url }}">Dashboard
                    {% if url == request.path %}
                        <span class="sr-only">(current)</span>
                    {% endif %}
                </a>
            </li>
            {% endwith %}
            {% with url = url_for('crud.create') %}
            <li class="nav-item {% if url == request.path %}active{% endif %}">
                <a class="nav-link" href="{{ url }}">Create Monkey
                    {% if url == request.path %}
                        <span class="sr-only">(current)</span>
                    {% endif %}
                </a>
            </li>
            {% endwith %}
        </ul>
    </div>
</nav>

barrel/templates/crud/includes/network.html
<table class="table table-hover table-dark table-sm">
    <tbody>
        {% for networkmonkey in network %}
        <tr>
            <td scope="row">
                {{ networkmonkey.name }}
            </td>
            <td>
                {% if networkmonkey.has_friendship %}
                    {% if monkey.best_friend != networkmonkey.id %}
                        <a href="{{ url_for('crud.set_best_friend', mnk_id=monkey.id, friend_id=networkmonkey.id) }}" class="btn btn-sm btn-primary">Make best</a>
                    {% else %}
                        <span class="badge badge-info">BEST</span>
                    {% endif %}
                {% endif %}

            </td>
            <td>
                {% if networkmonkey.has_friendship %}
                    <a href="{{ url_for('crud.undo_friendship', mnk_id=monkey.id, friend_id=networkmonkey.id) }}" class="float-right btn btn-sm btn-danger">Remove</a>
                {% else %}
                    <a href="{{ url_for('crud.make_friendship', mnk_id=monkey.id, friend_id=networkmonkey.id) }}" class="float-right btn btn-sm btn-primary">Add</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

barrel/templates/crud/includes/pages.html
<div class="container">
    <nav aria-label="">
        <ul class="pagination">
            {% for page_offset in pages %}
                <li class="page-item {% if offset == page_offset %}active{% endif %}">
                    <a class="page-link" href="?offset={{ page_offset }}&sort={{ filterform.sort.data }}&sort_by={{ filterform.sort_by.data }}">{{ loop.index }}</a></li>
            {% endfor %}
        </ul>
    </nav>
</div>